timeout 15
#shutdown_after_timeout
use_nvram false
resolution 1920 1080
use_graphics_for linux
showtools about, shell, mok_tool, firmware, reboot, shutdown
dont_scan_dirs ESP:/EFI/boot,EFI/memtest86,EFI/Linux,EFI/nixos
dont_scan_files OpenCore.efi mmx64.efi fbx64.efi shimx64.efi MokManager.efi systemd-bootx64.efi bootx64.efi grubx64_real.efi grubx64.efi vmlinuz-linux-zen archlinux.efi
extra_kernel_version_strings linux-lts,linux,linux-zen
#menuentry "Arch Linux" {
#   icon     /EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_arch.png
#   loader   /archlinux.efi
#}
menuentry "NixOS" {
    icon     /EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_nixos.org
    loader   /grub/x86_64-efi/grub.efi
}
menuentry "OpenCore" {
   icon    /EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_macos.png
   loader  /EFI/OC/OpenCore.efi
}
include themes/refind-theme-regular/theme.conf
